In [1]:
# Importing necessary libraries
import pandas as pd
import numpy as np

In [2]:
# Loading the healthcare dataset
health_data = pd.read_excel("../DATASETS/healthcare_dataset.csv.xlsx", engine='calamine')
health_data.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Aaron Adams,38,Female,O-,Cancer,2021-03-10,Norma Li,Hart LLC,UnitedHealthcare,26052.106404,363,Elective,2021-03-29,Lipitor,Inconclusive
1,Aaron Aguirre,36,Male,A-,Diabetes,2023-02-26,Katrina Luna,Murray-Shelton,UnitedHealthcare,27087.560553,300,Emergency,2023-03-13,Aspirin,Inconclusive
2,Aaron Anderson,50,Female,A+,Asthma,2020-12-18,Kenneth Jennings,Tanner-Cox,Cigna,39804.658624,196,Urgent,2021-01-15,Aspirin,Inconclusive
3,Aaron Anderson Md,20,Female,A-,Hypertension,2021-03-28,Tammy Perez,Ritter LLC,UnitedHealthcare,16846.415799,249,Elective,2021-04-09,Paracetamol,Abnormal
4,Aaron Archer,47,Female,B-,Cancer,2021-01-10,Cynthia Villanueva,"Montes Case and Mendez,",Medicare,10602.077185,108,Urgent,2021-01-17,Paracetamol,Inconclusive

In [3]:
# Getting information about the dataset
health_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  str
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  str
 3   Blood Type          55500 non-null  str
 4   Medical Condition   55500 non-null  str
 5   Date of Admission   55500 non-null  datetime64[us]
 6   Doctor              55500 non-null  str
 7   Hospital            55500 non-null  str
 8   Insurance Provider  55500 non-null  str
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  str
 12  Discharge Date      55500 non-null  datetime64[us]
 13  Medication          55500 non-null  str
 14  Test Results        55500 non-null  str
dtypes: datetime64[us](2), float64(1), int64(2), str(10)
memory usage: 11.2 MB

In [4]:
# the shape of the dataset
health_data.shape

(55500, 15)

In [5]:
# separating the columns into categorical and numerical columns
categorical_columns = health_data.select_dtypes(include=['str']).columns
numerical_columns = health_data.select_dtypes(include=['int64', 'float64']).columns

In [6]:
# categorical_columns, numerical_columns
categorical_columns, numerical_columns

(Index(['Name', 'Gender', 'Blood Type', 'Medical Condition', 'Doctor',
        'Hospital', 'Insurance Provider', 'Admission Type', 'Medication',
        'Test Results'],
       dtype='str'),
 Index(['Age', 'Billing Amount', 'Room Number'], dtype='str'))

In [7]:
# Summary statistics of the dataset
health_data.describe().T

,count,mean,min,25%,50%,75%,max,std
Age,55500.0,51.539459,13.0,35.0,52.0,68.0,89.0,19.602454
Date of Admission,55500,2021-11-01 01:02:22.443243,2019-05-08 00:00:00,2020-07-28 00:00:00,2021-11-01 00:00:00,2023-02-03 00:00:00,2024-05-07 00:00:00,NaN
Billing Amount,55500.0,25539.316097,-2008.49214,13241.224652,25538.069376,37820.508436,52764.276736,14211.454431
Room Number,55500.0,301.134829,101.0,202.0,302.0,401.0,500.0,115.243069
Discharge Date,55500,2021-11-16 13:15:20.821621,2019-05-09 00:00:00,2020-08-12 00:00:00,2021-11-17 00:00:00,2023-02-18 00:00:00,2024-06-06 00:00:00,NaN

### DATA CLEANING AND PREPARATION

In [8]:
# Checking for missing values in the dataset
missing_values = health_data.isnull().sum()
missing_values[missing_values > 0]

Series([], dtype: int64)

In [9]:
# checking for duplicate values in the dataset
duplicate_values = health_data.duplicated().sum()
duplicate_values

np.int64(534)

In [10]:
# Removing duplicate values from the dataset
health_data_cleaned = health_data.drop_duplicates()
health_data_cleaned.shape

(54966, 15)

In [20]:
# New Summary statistics of the dataset after removing duplicates
health_data_cleaned.describe().T

,count,mean,min,25%,50%,75%,max,std
Age,54966.0,51.535185,13.0,35.0,52.0,68.0,89.0,19.605661
Date of Admission,54966,2021-11-01 17:35:29.505512,2019-05-08 00:00:00,2020-07-28 00:00:00,2021-11-02 00:00:00,2023-02-03 00:00:00,2024-05-07 00:00:00,NaN
Billing Amount,54966.0,25544.306284,-2008.49214,13243.718641,25542.749145,37819.858159,52764.276736,14208.409711
Room Number,54966.0,301.124404,101.0,202.0,302.0,401.0,500.0,115.223143
Discharge Date,54966,2021-11-17 05:34:28.202161,2019-05-09 00:00:00,2020-08-13 00:00:00,2021-11-18 00:00:00,2023-02-19 00:00:00,2024-06-06 00:00:00,NaN

In [22]:
# saving the cleaned dataset to a new excel file
health_data_cleaned.to_excel("../DATASETS/healthcare_dataset_cleaned.xlsx", index=False)